# Gunakan base image Python
FROM python:3.12.4

# Set working directory
WORKDIR /app

# Copy file ke dalam container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port Flask
EXPOSE 5000

# Jalankan server flask
CMD ["python", "server.py"]
